language: go

go:
  - 1.10.x
  - 1.11.x

sudo: false

addons:
  apt:
    packages:
      - unzip

before_install:
  - mkdir -p $PWD/protoc /tmp/protobuf
  - wget -O $PWD/protoc/protoc https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.5.1-1/protoc-3.5.1-1-linux-x86_64.exe
  - wget -O /tmp/protobuf/protobuf.jar https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.jar
  - unzip -qq /tmp/protobuf/protobuf.jar -d /tmp/protobuf && mv /tmp/protobuf/google $PWD
  - chmod +x $PWD/protoc/protoc
  - export PATH=$PWD/protoc/:$PATH

install: true

script:
  # TODO: re-enable once we fix module support
  # - go test -v -short ./...
