// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata/src/util/imp/imp.gunk

/*
Package imp is a generated protocol buffer package.

It is generated from these files:
	testdata/src/util/imp/imp.gunk

It has these top-level messages:
	Message
*/
package imp

import proto1 "github.com/golang/protobuf/proto"
import fmt1 "fmt"
import math1 "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt1.Errorf
var _ = math1.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Msg string `protobuf:"bytes,0,,name=Msg" json:"Msg,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto1.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto1.RegisterType((*Message)(nil), "util/imp.Message")
}

func init() { proto1.RegisterFile("testdata/src/util/imp/imp.gunk", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x49, 0x2d, 0x2e,
	0x49, 0x49, 0x2c, 0x49, 0xd4, 0x2f, 0x2e, 0x4a, 0xd6, 0x2f, 0x2d, 0xc9, 0xcc, 0xd1, 0xcf, 0xcc,
	0x2d, 0x00, 0x61, 0xbd, 0xf4, 0xd2, 0xbc, 0x6c, 0x21, 0x0e, 0x98, 0x90, 0x92, 0x08, 0x17, 0xbb,
	0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x10, 0x27, 0x17, 0xb3, 0x6f, 0x71, 0xba, 0x04, 0x83,
	0x06, 0xa7, 0x13, 0x6b, 0x14, 0x73, 0x66, 0x6e, 0x41, 0x12, 0x5b, 0x41, 0x51, 0x7e, 0x49, 0xbe,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x0f, 0xf2, 0x69, 0x4f, 0x00, 0x00, 0x00,
}
