// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/gunk/opt/opt.gunk

/*
Package opt is a generated protocol buffer package.

Package opt provides the standard gunk protobuf options.

Generated by the gunkconv tool.

It is generated from these files:
	github.com/gunk/opt/opt.gunk

It has these top-level messages:
*/
package opt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Deprecated is the deprecated option.
type Deprecated int32

const ()

var Deprecated_name = map[int32]string{}
var Deprecated_value = map[string]int32{}

func (x Deprecated) String() string {
	return proto.EnumName(Deprecated_name, int32(x))
}
func (Deprecated) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// JavaPackage is the java_package option.
type JavaPackage int32

const ()

var JavaPackage_name = map[int32]string{}
var JavaPackage_value = map[string]int32{}

func (x JavaPackage) String() string {
	return proto.EnumName(JavaPackage_name, int32(x))
}
func (JavaPackage) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// JavaMultipleFiles is the java_multiple_files option.
type JavaMultipleFiles int32

const ()

var JavaMultipleFiles_name = map[int32]string{}
var JavaMultipleFiles_value = map[string]int32{}

func (x JavaMultipleFiles) String() string {
	return proto.EnumName(JavaMultipleFiles_name, int32(x))
}
func (JavaMultipleFiles) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterEnum("github.com/gunk/opt.Deprecated", Deprecated_name, Deprecated_value)
	proto.RegisterEnum("github.com/gunk/opt.JavaPackage", JavaPackage_name, JavaPackage_value)
	proto.RegisterEnum("github.com/gunk/opt.JavaMultipleFiles", JavaMultipleFiles_name, JavaMultipleFiles_value)
}

func init() { proto.RegisterFile("github.com/gunk/opt/opt.gunk", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2f, 0xcd, 0xcb, 0xd6, 0xcf, 0x2f, 0x28, 0x01,
	0x61, 0x3d, 0x10, 0x47, 0x48, 0x18, 0x8b, 0xac, 0x16, 0x0f, 0x17, 0x97, 0x4b, 0x6a, 0x41, 0x51,
	0x6a, 0x72, 0x62, 0x49, 0x6a, 0x8a, 0x16, 0x2f, 0x17, 0xb7, 0x57, 0x62, 0x59, 0x62, 0x40, 0x62,
	0x72, 0x76, 0x62, 0x7a, 0xaa, 0x96, 0x30, 0x97, 0x20, 0x88, 0xeb, 0x5b, 0x9a, 0x53, 0x92, 0x59,
	0x90, 0x93, 0xea, 0x96, 0x99, 0x93, 0x5a, 0xec, 0xc4, 0x1a, 0xc5, 0x9c, 0x5f, 0x50, 0x92, 0xc4,
	0x56, 0x50, 0x94, 0x5f, 0x92, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xda, 0x05, 0x07, 0x37,
	0x74, 0x00, 0x00, 0x00,
}
