package generate

import (
	"html/template"
	"io"

	"github.com/gunk/gunk/scopegen/parser"
)

var goTmpl = template.Must(template.New("").Parse(`// Code generated by "scopegen"; DO NOT EDIT.
package {{ .Package }}

type AuthScope string

{{ if .Scopes -}}
const (
{{- range $scope := .Scopes }}
	Scope_{{ $scope.Name }} AuthScope = "{{ $scope.Value }}"
{{- end }}
)

{{ end -}}
var AuthScopes = map[string][]AuthScope{
{{- range $method := .Methods }}
	"{{ $method.Name }}": []AuthScope{ {{- range $index, $scope := $method.Scopes }}{{ if $index }}, {{ end }}Scope_{{ $scope }}{{ end -}} },
{{- end }}
}
`))

// GO generates defined OAuth2 scopes for go programming languages.
func Go(w io.Writer, f *parser.File) error {
	return goTmpl.Execute(w, f)
}
