// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata.tld/util/imported/imp.gunk

package imported

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Message is a Echo message.
type Message struct {
	// Msg holds a message.
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_imp_a26ff03ad5a41588, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "testdata.v1.util.imported.Message")
}

func init() {
	proto.RegisterFile("testdata.tld/util/imported/imp.gunk", fileDescriptor_imp_a26ff03ad5a41588)
}

var fileDescriptor_imp_a26ff03ad5a41588 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x49, 0x2d, 0x2e,
	0x49, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0xc9, 0x49, 0xd1, 0x2f, 0x2d, 0xc9, 0xcc, 0xd1, 0xcf, 0xcc,
	0x2d, 0xc8, 0x2f, 0x2a, 0x49, 0x4d, 0x01, 0x31, 0xf4, 0xd2, 0x4b, 0xf3, 0xb2, 0x85, 0x24, 0xe1,
	0x8a, 0xca, 0x0c, 0xf5, 0x40, 0x6a, 0xf4, 0x60, 0x6a, 0x94, 0xc4, 0xb8, 0xd8, 0x7d, 0x53, 0x8b,
	0x8b, 0x13, 0xd3, 0x53, 0x85, 0xb8, 0xb9, 0x98, 0x7d, 0x8b, 0xd3, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x9d, 0xb8, 0xa2, 0x38, 0x60, 0x6a, 0x92, 0xd8, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x82, 0xe2, 0x17, 0xd9, 0x6c, 0x00, 0x00, 0x00,
}
