// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/gunk/opt/http/http.gunk

/*
Package http is a generated protocol buffer package.

Package http provides the http matching options for gunk.

It is generated from these files:
	github.com/gunk/opt/http/http.gunk

It has these top-level messages:
	Match
*/
package http

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Match is the http matching option.
type Match struct {
	Method string `protobuf:"bytes,0,,name=Method" json:"Method,omitempty"`
	Path   string `protobuf:"bytes,0,,name=Path" json:"Path,omitempty"`
	Body   string `protobuf:"bytes,0,,name=Body" json:"Body,omitempty"`
}

func (m *Match) Reset()                    { *m = Match{} }
func (m *Match) String() string            { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()               {}
func (*Match) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Match) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Match) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Match) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Match)(nil), "github.com/gunk/opt/http.Match")
}

func init() { proto.RegisterFile("github.com/gunk/opt/http/http.gunk", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2f, 0xcd, 0xcb, 0xd6, 0xcf, 0x2f, 0x28, 0xd1,
	0xcf, 0x28, 0x29, 0x29, 0x00, 0x13, 0x7a, 0x20, 0x21, 0x21, 0x09, 0x5c, 0x6a, 0x94, 0xd4, 0xb9,
	0x58, 0x7d, 0x13, 0x4b, 0x92, 0x33, 0x84, 0xb8, 0xb8, 0xd8, 0x7c, 0x53, 0x4b, 0x32, 0xf2, 0x53,
	0x34, 0x38, 0x85, 0x38, 0xb8, 0x58, 0x02, 0x12, 0x4b, 0x32, 0x20, 0x2c, 0xa7, 0xfc, 0x94, 0x4a,
	0x0d, 0x4e, 0x27, 0xb6, 0x28, 0x16, 0x90, 0x86, 0x24, 0xb6, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x16, 0x73, 0xd0, 0xea, 0x77, 0x00, 0x00, 0x00,
}
