// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata/echo.gunk

/*
Package testdata is a generated protocol buffer package.

package util contains a simple Echo service.

It is generated from these files:
	testdata/echo.gunk
	testdata/types.gunk

It has these top-level messages:
	Message
	CheckStatusResponse
*/
package testdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Empty from public import google/protobuf/empty.proto

// Status is a server health status.
type Status int32

const (
	// Status_Unknown is the default, unset status value.
	Status_Unknown Status = 0
	// Status_Error is a status value that implies something went wrong.
	Status_Error Status = 1
	// Status_OK is a status value used when all went well.
	Status_OK Status = 2
)

var Status_name = map[int32]string{
	0: "Unknown",
	1: "Error",
	2: "OK",
}
var Status_value = map[string]int32{
	"Unknown": 0,
	"Error":   1,
	"OK":      2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Message is a Echo message.
type Message struct {
	// Msg holds a message.
	Msg string `protobuf:"bytes,0,,name=Msg" json:"Msg,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// CheckStatusResponse is the response for a check status.
type CheckStatusResponse struct {
	Status Status `protobuf:"varint,1,,name=Status,enum=github.com.gunk.gunk.testdata.Status" json:"Status,omitempty"`
}

func (m *CheckStatusResponse) Reset()                    { *m = CheckStatusResponse{} }
func (m *CheckStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckStatusResponse) ProtoMessage()               {}
func (*CheckStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CheckStatusResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Unknown
}

func init() {
	proto.RegisterType((*Message)(nil), "github.com.gunk.gunk.testdata.Message")
	proto.RegisterType((*CheckStatusResponse)(nil), "github.com.gunk.gunk.testdata.CheckStatusResponse")
	proto.RegisterEnum("github.com.gunk.gunk.testdata.Status", Status_name, Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Util service

type UtilClient interface {
	// Echo echoes a message.
	Echo(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	// CheckStatus sends the server health status.
	CheckStatus(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*CheckStatusResponse, error)
}

type utilClient struct {
	cc *grpc.ClientConn
}

func NewUtilClient(cc *grpc.ClientConn) UtilClient {
	return &utilClient{cc}
}

func (c *utilClient) Echo(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/github.com.gunk.gunk.testdata.Util/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *utilClient) CheckStatus(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*CheckStatusResponse, error) {
	out := new(CheckStatusResponse)
	err := grpc.Invoke(ctx, "/github.com.gunk.gunk.testdata.Util/CheckStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Util service

type UtilServer interface {
	// Echo echoes a message.
	Echo(context.Context, *Message) (*Message, error)
	// CheckStatus sends the server health status.
	CheckStatus(context.Context, *google_protobuf.Empty) (*CheckStatusResponse, error)
}

func RegisterUtilServer(s *grpc.Server, srv UtilServer) {
	s.RegisterService(&_Util_serviceDesc, srv)
}

func _Util_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.gunk.gunk.testdata.Util/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilServer).Echo(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Util_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.gunk.gunk.testdata.Util/CheckStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilServer).CheckStatus(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Util_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.gunk.gunk.testdata.Util",
	HandlerType: (*UtilServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Util_Echo_Handler,
		},
		{
			MethodName: "CheckStatus",
			Handler:    _Util_CheckStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testdata/echo.gunk",
}

func init() { proto.RegisterFile("testdata/echo.gunk", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x49, 0x2d, 0x2e,
	0x49, 0x49, 0x2c, 0x49, 0xd4, 0x4f, 0x4d, 0xce, 0xc8, 0xd7, 0x4b, 0x2f, 0xcd, 0xcb, 0x16, 0x92,
	0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0x05, 0x0b, 0x40, 0x08, 0x98, 0x42,
	0x29, 0xe9, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0xfd, 0x82, 0xa2, 0xfc, 0x92, 0xfc, 0xa4, 0xd2,
	0x34, 0xfd, 0xd4, 0xdc, 0x82, 0x92, 0x4a, 0x3d, 0x30, 0x57, 0x49, 0x84, 0x8b, 0xdd, 0x37, 0xb5,
	0xb8, 0x38, 0x31, 0x3d, 0x55, 0x88, 0x93, 0x8b, 0xd9, 0xb7, 0x38, 0x5d, 0x82, 0x41, 0x83, 0x53,
	0xc9, 0x8b, 0x4b, 0xd8, 0x39, 0x23, 0x35, 0x39, 0x3b, 0xb8, 0x24, 0xb1, 0xa4, 0xb4, 0x38, 0x28,
	0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0xc8, 0x98, 0x8b, 0x0d, 0x22, 0x22, 0xc1, 0xa8, 0xc1,
	0x67, 0xa4, 0xaa, 0x87, 0xd7, 0x5e, 0x3d, 0x88, 0x52, 0x2d, 0x0d, 0x98, 0x26, 0x21, 0x6e, 0x2e,
	0xf6, 0xd0, 0xbc, 0xec, 0xbc, 0xfc, 0xf2, 0x3c, 0x01, 0x06, 0x21, 0x4e, 0x2e, 0x56, 0xd7, 0xa2,
	0xa2, 0xfc, 0x22, 0x01, 0x46, 0x21, 0x36, 0x2e, 0x26, 0x7f, 0x6f, 0x01, 0x26, 0xa3, 0x9d, 0x8c,
	0x5c, 0x2c, 0xa1, 0x25, 0x99, 0x39, 0x42, 0x61, 0x5c, 0x2c, 0xae, 0xc9, 0x19, 0xf9, 0x42, 0x6a,
	0x04, 0x6c, 0x80, 0xba, 0x5c, 0x8a, 0x48, 0x75, 0x42, 0x91, 0x5c, 0xdc, 0x48, 0xde, 0x12, 0x12,
	0xd3, 0x83, 0x84, 0x8c, 0x1e, 0x2c, 0x64, 0xf4, 0x5c, 0x41, 0x21, 0x23, 0x65, 0x44, 0xc0, 0x38,
	0x2c, 0x41, 0xe3, 0xc4, 0x15, 0xc5, 0x01, 0x93, 0x0f, 0x60, 0x48, 0x62, 0x03, 0x9b, 0x68, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x38, 0x4f, 0xb0, 0x94, 0xae, 0x01, 0x00, 0x00,
}
